import { useRegion } from "./region";

type UILang = "de" | "en" | "fr" | "it";

export const UI = {
  de: {
    nav: {
      home: "Home",
      homeSub: "",
      jobcheck: "JobCheck",
      jobcheckSub: "Stellenanalyse",
      matchcheck: "MatchCheck",
      matchcheckSub: "Stelle ↔ Person",
      teamcheck: "TeamCheck",
      teamcheckSub: "Teamstruktur",
      coach: "Louis (KI-Coach)",
      coachSub: "Führung & Entwicklung",
      courses: "Kursbereich",
      coursesSub: "Lernmodule",
      regionTitle: "Sprachregion",
      regionLabel: (l: string) => `Sprachregion: ${l}`,
      firmaDashboard: "Firmen-Dashboard",
      userManagement: "Benutzerverwaltung",
      logout: "Abmelden",
    },
    footer: {
      aiQuotaTitle: (used: number, total: number, reset: string) =>
        `${used} von ${total} KI-Anfragen genutzt\nAutomatische Zurücksetzung am ${reset}`,
      aiPrefix: "KI:",
      aiOf: "von",
      aiLeft: "übrig",
      resetOn: "Reset am",
      accessUntil: "Freigeschaltet bis:",
      imprint: "Impressum",
      privacy: "Datenschutz",
      disclaimer: "Disclaimer",
    },
    region: {
      DE: "Deutschland",
      CH: "Schweiz",
      AT: "Österreich",
      EN: "English",
      FR: "Français",
      IT: "Italiano",
    },
    home: {
      resetTitle: "Bist du sicher?",
      resetBody: "Alle eingegebenen Daten werden gelöscht.",
      cancel: "Abbrechen",
      continue: "Weiter",
      fileError: "Die Datei konnte nicht gelesen werden.",
      jobcheckTitle: "Stellenanalyse",
      jobcheckSubtitle: "Strukturelle Passung für sichere Besetzungsentscheidungen",
      jobcheckDesc: "Definiere eine Stelle und analysiere die strukturelle Passung. Die Analyse liefert klare Handlungsempfehlungen für Besetzung, Führung und Zusammenarbeit.",
      newAnalysis: "Neue Analyse",
      openAnalysis: "Analyse öffnen",
      jobcheckBullets: [
        "Wissenschaftlich fundierte Methodik",
        "Klare Entscheidungsstruktur",
        "Objektive Personalentscheidungen",
        "Transparente Ergebnislogik",
        "Reduziert Fehlbesetzungsrisiken",
        "Passgenaue Rollenbesetzung",
      ],
      coachTitle: "Louis",
      coachSubtitle: "Coach für Entscheidungen im richtigen Moment",
      coachDesc: "Nutze Louis für Recruiting, Teamfragen, Gesprächsvorbereitung und konkrete Handlungsempfehlungen – jederzeit, auch ohne Analyse.",
      openCoach: "Louis öffnen",
      coachBullets: [
        "Recruiting und Stellenanzeigen",
        "Gesprächsvorbereitung",
        "Analyse von Teamkonstellationen",
        "Konfliktmuster erkennen und lösen",
        "Rollenspiele und Gesprächssimulation",
        "Quellenbasierte Führungsberatung",
      ],
    },
    coach: {
      pageTitle: "Louis",
      pageSubtitle: "Dein KI-Coach für Führung, HR und Teamfragen",
      profileActive: "Profil aktiv",
      historyTitle: "Verlauf",
      historyButtonTitle: "Gesprächsverlauf",
      newConvTitle: "Neue Unterhaltung",
      newConvButton: "Neue Unterhaltung",
      exportTitle: "Gespräch als TXT exportieren",
      clearChatTitle: "Gespräch löschen",
      clearChatConfirm: "Möchtest du das aktuelle Gespräch wirklich löschen?",
      historySearchPlaceholder: "Verlauf durchsuchen...",
      noHits: "Keine Treffer.",
      noConversations: "Noch keine gespeicherten Gespräche.",
      renameTitle: "Umbenennen",
      pinTitle: "Anpinnen",
      unpinTitle: "Lösen",
      deleteTitle: "Löschen",
      deleteConvConfirm: "Diese Unterhaltung wirklich löschen?",
      inputDesc: "Stell eine Frage zu Führung, Teamdynamik, Kommunikation oder nutze einen Musterprompt.",
      promptSearchPlaceholder: "Musterprompt suchen…",
      examplePromptsBtn: "Musterprompts",
      noPromptResults: (q: string) => `Keine Prompts gefunden für „${q}"`,
      requireAnalysisTitle: "Bitte zuerst eine Stelle analysieren",
      copyAnswer: "Antwort kopieren",
      goldenSaved: "Als Golden Answer gespeichert",
      goldenSave: "Als Golden Answer speichern (Admin)",
      suggestionsLabel: "Vorschläge",
      loadingDefault: "Antwort wird erstellt...",
      inputPlaceholder: "Frage stellen...",
      uploadImage: "Bild hochladen",
      uploadDoc: "PDF / Textdokument hochladen",
      errorOverloaded: "Der Coach ist gerade kurz überlastet – bitte in ein paar Sekunden nochmal probieren.",
      errorQuota: "Das KI-Kontingent eurer Organisation ist leider aufgebraucht. Bitte wende dich an euren Administrator, um das Limit zu erhöhen oder den Zähler zurückzusetzen.",
      errorTimeout: "Die Anfrage hat zu lange gedauert. Bitte versuche es erneut – bei komplexen Fragen kann es helfen, die Frage kürzer zu formulieren.",
      errorTimeoutShort: "Die Anfrage hat zu lange gedauert. Bitte versuche es erneut.",
      errorTech: "Entschuldigung, es ist ein technisches Problem aufgetreten. Bitte versuche es erneut.",
      exportHeader: "Louis – Gesprächsprotokoll",
      exportedAt: (d: string, t: string) => `Exportiert am ${d} um ${t}`,
      exportLabelQuestion: "Frage",
      exportLabelCoach: "Coach",
      welcome: "Willkommen bei Louis – deinem bioLogic Coach für Entscheidungen im richtigen Moment.\n\nIch unterstütze dich bei Fragen rund um Führung, Personalentscheidungen, Assessment, Bewerbungsgespräche und Kommunikation.\n\nWie kann ich dir helfen?",
      imageWithText: "Bild mit Text",
      imageDownload: "Bild herunterladen",
      imageOnly: "Nur Bild (ohne Text)",
      attachmentAlt: "Anhang",
      docReading: "Dokument wird gelesen...",
      roleRequired: "(Stelle erforderlich)",
      aiImageNote: "[KI-generiertes Bild wurde in diesem Schritt erstellt]",
    },
    jobcheck: {
      pageTitle: "bioLogic JobCheck",
      pageSubtitle: "Bewerte die strukturelle Passung zwischen Stellenprofil und Personenprofil.",
      printButton: "Drucken",
      printTooltip: "Im Druckdialog 'Als PDF speichern' wählen",
      noAnalysisTitle: "Keine Analyse vorhanden",
      noAnalysisDesc: "Erstelle zuerst ein Stellenprofil, um den JobCheck durchzuführen.",
      gotoDataEntry: "Zur Datenerfassung",
      summaryRole: "Stelle",
      summaryTaskStructure: "Aufgabenstruktur",
      summaryWorkStyle: "Arbeitsweise",
      summarySuccessFocus: "Erfolgsfokus",
      summaryLeadership: "Führung",
      summaryCompetenceCount: "Kompetenzanzahl",
      summaryNotDefined: "Nicht definiert",
      countActivities: "Tätigkeiten",
      countHumanSkills: "Humankompetenzen",
      countLeadership: "Führung",
      taskStructureLabels: {
        "überwiegend operativ": "Praktische Umsetzung im Tagesgeschäft",
        "überwiegend systemisch": "Abstimmung und Umsetzung im Arbeitsablauf",
        "überwiegend strategisch": "Analyse, Planung und strategische Steuerung",
        "Gemischt": "Ausgewogene Mischung",
      } as Record<string, string>,
      workStyleLabels: {
        "Umsetzungsorientiert": "Umsetzung und Ergebnisse",
        "Daten-/prozessorientiert": "Analyse und Struktur",
        "Menschenorientiert": "Zusammenarbeit und Kommunikation",
        "Ausgewogen": "Ausgewogene Mischung",
      } as Record<string, string>,
      leadershipLabels: {
        "Keine": "Keine Führungsverantwortung",
        "Projekt-/Teamkoordination": "Projekt- oder Teamkoordination",
        "Fachliche Führung": "Fachliche Führung",
        "Disziplinarische Führung mit Ergebnisverantwortung": "Führung mit Personalverantwortung",
      } as Record<string, string>,
      successFocusLabels: [
        "Ergebnisse und Zielerreichung",
        "Zusammenarbeit und Netzwerk",
        "Innovation und Veränderung",
        "Prozesse und Effizienz",
        "Fachliche Qualität und Expertise",
        "Kommunikation und Einfluss",
      ] as string[],
      analyseAccordionTitle: "Analyse – Soll / Ist Profil",
      reportAccordionTitle: "JobCheck Bericht",
      sollHeader: "Sollprofil (Stelle)",
      istHeader: "Istprofil (Person)",
      istDescription: "Verschiebe die Regler, um das Personenprofil einzugeben. Die Werte werden automatisch normalisiert.",
      labelImpulsiv: "Impulsiv",
      labelIntuitiv: "Intuitiv",
      labelAnalytisch: "Analytisch",
      normalizedNote: "Normalisiertes Profil (max. 67 % pro Komponente)",
      roleDominanceText: (compLabel: string, dominanceText: string) =>
        `Die dominante Logik der Stelle ist ${compLabel} geprägt: ${dominanceText}.`,
      candDominancePrefix: "Die dominante Logik der Person ist ",
      candDominanceMiddle: " geprägt: ",
      createReportButton: "Bericht erstellen",
      reportEmptyHint: "Bitte zuerst das Ist-Profil eingeben und „Bericht erstellen\" klicken.",
    },
    teamcheckReport: {
      loadingTitle: "TeamCheck wird erstellt",
      loadingBody: "Die Texte werden gerade auf Basis des Profils generiert. Das dauert in der Regel 15–25 Sekunden.",
    },
  },
  en: {
    nav: {
      home: "Home",
      homeSub: "",
      jobcheck: "JobCheck",
      jobcheckSub: "Role analysis",
      matchcheck: "MatchCheck",
      matchcheckSub: "Role ↔ Person",
      teamcheck: "TeamCheck",
      teamcheckSub: "Team structure",
      coach: "Louis (AI Coach)",
      coachSub: "Leadership & development",
      courses: "Courses",
      coursesSub: "Learning modules",
      regionTitle: "Language region",
      regionLabel: (l: string) => `Language region: ${l}`,
      firmaDashboard: "Company dashboard",
      userManagement: "User management",
      logout: "Log out",
    },
    footer: {
      aiQuotaTitle: (used: number, total: number, reset: string) =>
        `${used} of ${total} AI requests used\nAutomatic reset on ${reset}`,
      aiPrefix: "AI:",
      aiOf: "of",
      aiLeft: "left",
      resetOn: "Reset on",
      accessUntil: "Access until:",
      imprint: "Imprint",
      privacy: "Privacy",
      disclaimer: "Disclaimer",
    },
    region: {
      DE: "Germany",
      CH: "Switzerland",
      AT: "Austria",
      EN: "English",
      FR: "Français",
      IT: "Italiano",
    },
    home: {
      resetTitle: "Are you sure?",
      resetBody: "All entered data will be deleted.",
      cancel: "Cancel",
      continue: "Continue",
      fileError: "The file could not be read.",
      jobcheckTitle: "Role analysis",
      jobcheckSubtitle: "Structural fit for confident hiring decisions",
      jobcheckDesc: "Define a role and analyse its structural fit. The analysis delivers clear recommendations for hiring, leadership and collaboration.",
      newAnalysis: "New analysis",
      openAnalysis: "Open analysis",
      jobcheckBullets: [
        "Scientifically grounded methodology",
        "Clear decision structure",
        "Objective people decisions",
        "Transparent reasoning",
        "Reduces mis-hire risk",
        "Precise role placement",
      ],
      coachTitle: "Louis",
      coachSubtitle: "Coach for decisions at the right moment",
      coachDesc: "Use Louis for recruiting, team questions, interview preparation and concrete recommendations – anytime, even without an analysis.",
      openCoach: "Open Louis",
      coachBullets: [
        "Recruiting and job postings",
        "Interview preparation",
        "Analysing team constellations",
        "Spotting and resolving conflict patterns",
        "Role play and conversation simulation",
        "Source-based leadership advice",
      ],
    },
    coach: {
      pageTitle: "Louis",
      pageSubtitle: "Your AI coach for leadership, HR and team questions",
      profileActive: "Profile active",
      historyTitle: "History",
      historyButtonTitle: "Conversation history",
      newConvTitle: "New conversation",
      newConvButton: "New conversation",
      exportTitle: "Export conversation as TXT",
      clearChatTitle: "Delete conversation",
      clearChatConfirm: "Do you really want to delete the current conversation?",
      historySearchPlaceholder: "Search history...",
      noHits: "No results.",
      noConversations: "No saved conversations yet.",
      renameTitle: "Rename",
      pinTitle: "Pin",
      unpinTitle: "Unpin",
      deleteTitle: "Delete",
      deleteConvConfirm: "Really delete this conversation?",
      inputDesc: "Ask a question about leadership, team dynamics, communication or pick an example prompt.",
      promptSearchPlaceholder: "Search example prompts…",
      examplePromptsBtn: "Example prompts",
      noPromptResults: (q: string) => `No prompts found for „${q}"`,
      requireAnalysisTitle: "Please analyse a role first",
      copyAnswer: "Copy answer",
      goldenSaved: "Saved as Golden Answer",
      goldenSave: "Save as Golden Answer (admin)",
      suggestionsLabel: "Suggestions",
      loadingDefault: "Generating answer...",
      inputPlaceholder: "Ask a question...",
      uploadImage: "Upload image",
      uploadDoc: "Upload PDF / text document",
      errorOverloaded: "The coach is briefly overloaded – please try again in a few seconds.",
      errorQuota: "Your organisation's AI quota has been used up. Please contact your administrator to raise the limit or reset the counter.",
      errorTimeout: "The request took too long. Please try again – for complex questions it can help to phrase them more briefly.",
      errorTimeoutShort: "The request took too long. Please try again.",
      errorTech: "Sorry, a technical problem occurred. Please try again.",
      exportHeader: "Louis – conversation transcript",
      exportedAt: (d: string, t: string) => `Exported on ${d} at ${t}`,
      exportLabelQuestion: "Question",
      exportLabelCoach: "Coach",
      welcome: "Welcome to Louis – your bioLogic coach for decisions at the right moment.\n\nI support you with questions on leadership, people decisions, assessment, interviews and communication.\n\nHow can I help you?",
      imageWithText: "Image with text",
      imageDownload: "Download image",
      imageOnly: "Image only (no text)",
      attachmentAlt: "Attachment",
      docReading: "Reading document...",
      roleRequired: "(role required)",
      aiImageNote: "[An AI-generated image was created in this step]",
    },
    jobcheck: {
      pageTitle: "bioLogic JobCheck",
      pageSubtitle: "Assess the structural fit between the role profile and the person profile.",
      printButton: "Print",
      printTooltip: "Choose 'Save as PDF' in the print dialog",
      noAnalysisTitle: "No analysis available",
      noAnalysisDesc: "Create a role profile first to run the JobCheck.",
      gotoDataEntry: "Go to data entry",
      summaryRole: "Role",
      summaryTaskStructure: "Task structure",
      summaryWorkStyle: "Work style",
      summarySuccessFocus: "Success focus",
      summaryLeadership: "Leadership",
      summaryCompetenceCount: "Competence count",
      summaryNotDefined: "Not defined",
      countActivities: "activities",
      countHumanSkills: "human skills",
      countLeadership: "leadership",
      taskStructureLabels: {
        "überwiegend operativ": "Hands-on delivery in day-to-day work",
        "überwiegend systemisch": "Coordination and execution within the workflow",
        "überwiegend strategisch": "Analysis, planning and strategic steering",
        "Gemischt": "Balanced mix",
      } as Record<string, string>,
      workStyleLabels: {
        "Umsetzungsorientiert": "Delivery and results",
        "Daten-/prozessorientiert": "Analysis and structure",
        "Menschenorientiert": "Collaboration and communication",
        "Ausgewogen": "Balanced mix",
      } as Record<string, string>,
      leadershipLabels: {
        "Keine": "No leadership responsibility",
        "Projekt-/Teamkoordination": "Project or team coordination",
        "Fachliche Führung": "Functional leadership",
        "Disziplinarische Führung mit Ergebnisverantwortung": "Leadership with people responsibility",
      } as Record<string, string>,
      successFocusLabels: [
        "Results and goal achievement",
        "Collaboration and network",
        "Innovation and change",
        "Processes and efficiency",
        "Functional quality and expertise",
        "Communication and influence",
      ] as string[],
      analyseAccordionTitle: "Analysis – Target / Actual profile",
      reportAccordionTitle: "JobCheck report",
      sollHeader: "Target profile (role)",
      istHeader: "Actual profile (person)",
      istDescription: "Move the sliders to enter the person profile. Values are normalised automatically.",
      labelImpulsiv: "Impulsive",
      labelIntuitiv: "Intuitive",
      labelAnalytisch: "Analytical",
      normalizedNote: "Normalised profile (max. 67 % per component)",
      roleDominanceText: (compLabel: string, dominanceText: string) =>
        `The dominant logic of the role is ${compLabel}: ${dominanceText}.`,
      candDominancePrefix: "The dominant logic of the person is ",
      candDominanceMiddle: ": ",
      createReportButton: "Create report",
      reportEmptyHint: "Please enter the actual profile first and click \"Create report\".",
    },
    teamcheckReport: {
      loadingTitle: "Generating team analysis",
      loadingBody: "We're writing the report based on the profile. This usually takes 15–25 seconds.",
    },
  },
  fr: {
    nav: {
      home: "Accueil",
      homeSub: "",
      jobcheck: "JobCheck",
      jobcheckSub: "Analyse de poste",
      matchcheck: "MatchCheck",
      matchcheckSub: "Poste ↔ Personne",
      teamcheck: "TeamCheck",
      teamcheckSub: "Structure d'équipe",
      coach: "Louis (Coach IA)",
      coachSub: "Leadership & développement",
      courses: "Formation",
      coursesSub: "Modules d'apprentissage",
      regionTitle: "Région linguistique",
      regionLabel: (l: string) => `Région : ${l}`,
      firmaDashboard: "Tableau de bord",
      userManagement: "Gestion des utilisateurs",
      logout: "Se déconnecter",
    },
    footer: {
      aiQuotaTitle: (used: number, total: number, reset: string) =>
        `${used} sur ${total} requêtes IA utilisées\nRéinitialisation automatique le ${reset}`,
      aiPrefix: "IA :",
      aiOf: "sur",
      aiLeft: "restantes",
      resetOn: "Réinitialisation le",
      accessUntil: "Accès jusqu'au :",
      imprint: "Mentions légales",
      privacy: "Confidentialité",
      disclaimer: "Avertissement",
    },
    region: {
      DE: "Allemagne",
      CH: "Suisse",
      AT: "Autriche",
      EN: "Anglais",
      FR: "Français",
      IT: "Italiano",
    },
    home: {
      resetTitle: "Êtes-vous sûr ?",
      resetBody: "Toutes les données saisies seront supprimées.",
      cancel: "Annuler",
      continue: "Continuer",
      fileError: "Le fichier n'a pas pu être lu.",
      jobcheckTitle: "Analyse de poste",
      jobcheckSubtitle: "Adéquation structurelle pour des décisions de recrutement fiables",
      jobcheckDesc: "Définissez un poste et analysez son adéquation structurelle. L'analyse fournit des recommandations claires pour le recrutement, le management et la collaboration.",
      newAnalysis: "Nouvelle analyse",
      openAnalysis: "Ouvrir l'analyse",
      jobcheckBullets: [
        "Méthodologie scientifique",
        "Structure de décision claire",
        "Décisions RH objectives",
        "Logique de résultats transparente",
        "Réduit les risques de mauvais recrutement",
        "Adéquation précise au poste",
      ],
      coachTitle: "Louis",
      coachSubtitle: "Coach pour des décisions au bon moment",
      coachDesc: "Utilisez Louis pour le recrutement, les questions d'équipe, la préparation d'entretien et des recommandations concrètes — à tout moment, même sans analyse.",
      openCoach: "Ouvrir Louis",
      coachBullets: [
        "Recrutement et offres d'emploi",
        "Préparation d'entretien",
        "Analyse des dynamiques d'équipe",
        "Identifier et résoudre les conflits",
        "Jeux de rôle et simulation de conversation",
        "Conseils en leadership basés sur des sources",
      ],
    },
    coach: {
      pageTitle: "Louis",
      pageSubtitle: "Votre coach IA pour le leadership, les RH et les équipes",
      profileActive: "Profil actif",
      historyTitle: "Historique",
      historyButtonTitle: "Historique des conversations",
      newConvTitle: "Nouvelle conversation",
      newConvButton: "Nouvelle conversation",
      exportTitle: "Exporter la conversation en TXT",
      clearChatTitle: "Supprimer la conversation",
      clearChatConfirm: "Voulez-vous vraiment supprimer la conversation en cours ?",
      historySearchPlaceholder: "Rechercher dans l'historique...",
      noHits: "Aucun résultat.",
      noConversations: "Aucune conversation sauvegardée.",
      renameTitle: "Renommer",
      pinTitle: "Épingler",
      unpinTitle: "Désépingler",
      deleteTitle: "Supprimer",
      deleteConvConfirm: "Supprimer cette conversation ?",
      inputDesc: "Posez une question sur le leadership, la dynamique d'équipe, la communication ou choisissez un exemple de prompt.",
      promptSearchPlaceholder: "Rechercher un exemple de prompt…",
      examplePromptsBtn: "Exemples de prompts",
      noPromptResults: (q: string) => `Aucun prompt trouvé pour « ${q} »`,
      requireAnalysisTitle: "Veuillez d'abord analyser un poste",
      copyAnswer: "Copier la réponse",
      goldenSaved: "Enregistré comme réponse de référence",
      goldenSave: "Enregistrer comme réponse de référence (admin)",
      suggestionsLabel: "Suggestions",
      loadingDefault: "Génération de la réponse...",
      inputPlaceholder: "Posez une question...",
      uploadImage: "Télécharger une image",
      uploadDoc: "Télécharger un PDF / document texte",
      errorOverloaded: "Le coach est momentanément surchargé — veuillez réessayer dans quelques secondes.",
      errorQuota: "Le quota IA de votre organisation est épuisé. Veuillez contacter votre administrateur pour augmenter la limite ou réinitialiser le compteur.",
      errorTimeout: "La requête a pris trop de temps. Veuillez réessayer — pour les questions complexes, formulez-les plus brièvement.",
      errorTimeoutShort: "La requête a pris trop de temps. Veuillez réessayer.",
      errorTech: "Désolé, un problème technique s'est produit. Veuillez réessayer.",
      exportHeader: "Louis — Transcript de conversation",
      exportedAt: (d: string, t: string) => `Exporté le ${d} à ${t}`,
      exportLabelQuestion: "Question",
      exportLabelCoach: "Coach",
      welcome: "Bienvenue chez Louis — votre coach bioLogic pour des décisions au bon moment.\n\nJe vous accompagne sur les questions de leadership, de décisions RH, d'assessment, d'entretiens et de communication.\n\nComment puis-je vous aider ?",
      imageWithText: "Image avec texte",
      imageDownload: "Télécharger l'image",
      imageOnly: "Image seule (sans texte)",
      attachmentAlt: "Pièce jointe",
      docReading: "Lecture du document...",
      roleRequired: "(poste requis)",
      aiImageNote: "[Une image générée par IA a été créée à cette étape]",
    },
    jobcheck: {
      pageTitle: "bioLogic JobCheck",
      pageSubtitle: "Évaluez l'adéquation structurelle entre le profil de poste et le profil de la personne.",
      printButton: "Imprimer",
      printTooltip: "Choisissez « Enregistrer en PDF » dans la boîte de dialogue d'impression",
      noAnalysisTitle: "Aucune analyse disponible",
      noAnalysisDesc: "Créez d'abord un profil de poste pour lancer le JobCheck.",
      gotoDataEntry: "Aller à la saisie",
      summaryRole: "Poste",
      summaryTaskStructure: "Structure des tâches",
      summaryWorkStyle: "Style de travail",
      summarySuccessFocus: "Axes de succès",
      summaryLeadership: "Management",
      summaryCompetenceCount: "Nombre de compétences",
      summaryNotDefined: "Non défini",
      countActivities: "activités",
      countHumanSkills: "compétences humaines",
      countLeadership: "management",
      taskStructureLabels: {
        "überwiegend operativ": "Exécution opérationnelle au quotidien",
        "überwiegend systemisch": "Coordination et exécution dans le flux de travail",
        "überwiegend strategisch": "Analyse, planification et pilotage stratégique",
        "Gemischt": "Mélange équilibré",
      } as Record<string, string>,
      workStyleLabels: {
        "Umsetzungsorientiert": "Réalisation et résultats",
        "Daten-/prozessorientiert": "Analyse et structure",
        "Menschenorientiert": "Collaboration et communication",
        "Ausgewogen": "Mélange équilibré",
      } as Record<string, string>,
      leadershipLabels: {
        "Keine": "Aucune responsabilité managériale",
        "Projekt-/Teamkoordination": "Coordination de projet ou d'équipe",
        "Fachliche Führung": "Encadrement fonctionnel",
        "Disziplinarische Führung mit Ergebnisverantwortung": "Management avec responsabilité de résultats",
      } as Record<string, string>,
      successFocusLabels: [
        "Résultats et atteinte des objectifs",
        "Collaboration et réseau",
        "Innovation et changement",
        "Processus et efficacité",
        "Qualité et expertise métier",
        "Communication et influence",
      ] as string[],
      analyseAccordionTitle: "Analyse — Profil cible / réel",
      reportAccordionTitle: "Rapport JobCheck",
      sollHeader: "Profil cible (poste)",
      istHeader: "Profil réel (personne)",
      istDescription: "Déplacez les curseurs pour saisir le profil de la personne. Les valeurs sont normalisées automatiquement.",
      labelImpulsiv: "Rythme et Décision",
      labelIntuitiv: "Communication et Relations",
      labelAnalytisch: "Structure et Rigueur",
      normalizedNote: "Profil normalisé (max. 67 % par composante)",
      roleDominanceText: (compLabel: string, dominanceText: string) =>
        `La logique dominante du poste est ${compLabel} : ${dominanceText}.`,
      candDominancePrefix: "La logique dominante de la personne est ",
      candDominanceMiddle: " : ",
      createReportButton: "Créer le rapport",
      reportEmptyHint: "Veuillez d'abord saisir le profil réel et cliquer sur « Créer le rapport ».",
    },
    teamcheckReport: {
      loadingTitle: "Génération de l'analyse d'équipe",
      loadingBody: "Les textes sont générés sur la base du profil. Cela prend généralement 15 à 25 secondes.",
    },
  },
  it: {
    nav: {
      home: "Home",
      homeSub: "",
      jobcheck: "JobCheck",
      jobcheckSub: "Analisi del ruolo",
      matchcheck: "MatchCheck",
      matchcheckSub: "Ruolo ↔ Persona",
      teamcheck: "TeamCheck",
      teamcheckSub: "Struttura del team",
      coach: "Louis (Coach IA)",
      coachSub: "Leadership e sviluppo",
      courses: "Formazione",
      coursesSub: "Moduli di apprendimento",
      regionTitle: "Regione linguistica",
      regionLabel: (l: string) => `Regione: ${l}`,
      firmaDashboard: "Dashboard aziendale",
      userManagement: "Gestione utenti",
      logout: "Esci",
    },
    footer: {
      aiQuotaTitle: (used: number, total: number, reset: string) =>
        `${used} di ${total} richieste IA utilizzate\nReset automatico il ${reset}`,
      aiPrefix: "IA:",
      aiOf: "di",
      aiLeft: "rimaste",
      resetOn: "Reset il",
      accessUntil: "Accesso fino al:",
      imprint: "Note legali",
      privacy: "Privacy",
      disclaimer: "Disclaimer",
    },
    region: {
      DE: "Germania",
      CH: "Svizzera",
      AT: "Austria",
      EN: "Inglese",
      FR: "Francese",
      IT: "Italiano",
    },
    home: {
      resetTitle: "Sei sicuro?",
      resetBody: "Tutti i dati inseriti verranno eliminati.",
      cancel: "Annulla",
      continue: "Continua",
      fileError: "Il file non ha potuto essere letto.",
      jobcheckTitle: "Analisi del ruolo",
      jobcheckSubtitle: "Adeguatezza strutturale per decisioni di selezione sicure",
      jobcheckDesc: "Definisci un ruolo e analizza la sua adeguatezza strutturale. L'analisi fornisce raccomandazioni chiare per la selezione, la leadership e la collaborazione.",
      newAnalysis: "Nuova analisi",
      openAnalysis: "Apri l'analisi",
      jobcheckBullets: [
        "Metodologia scientificamente fondata",
        "Struttura decisionale chiara",
        "Decisioni HR obiettive",
        "Logica dei risultati trasparente",
        "Riduce i rischi di selezione errata",
        "Posizionamento preciso nel ruolo",
      ],
      coachTitle: "Louis",
      coachSubtitle: "Coach per le decisioni nel momento giusto",
      coachDesc: "Usa Louis per il recruiting, le domande di team, la preparazione ai colloqui e raccomandazioni concrete, in qualsiasi momento, anche senza analisi.",
      openCoach: "Apri Louis",
      coachBullets: [
        "Recruiting e offerte di lavoro",
        "Preparazione al colloquio",
        "Analisi delle dinamiche di team",
        "Individuare e risolvere i conflitti",
        "Role play e simulazione di conversazione",
        "Consulenza di leadership basata su fonti",
      ],
    },
    coach: {
      pageTitle: "Louis",
      pageSubtitle: "Il tuo coach IA per leadership, HR e team",
      profileActive: "Profilo attivo",
      historyTitle: "Cronologia",
      historyButtonTitle: "Cronologia conversazioni",
      newConvTitle: "Nuova conversazione",
      newConvButton: "Nuova conversazione",
      exportTitle: "Esporta conversazione come TXT",
      clearChatTitle: "Elimina conversazione",
      clearChatConfirm: "Vuoi davvero eliminare la conversazione corrente?",
      historySearchPlaceholder: "Cerca nella cronologia...",
      noHits: "Nessun risultato.",
      noConversations: "Nessuna conversazione salvata.",
      renameTitle: "Rinomina",
      pinTitle: "Fissa",
      unpinTitle: "Rimuovi",
      deleteTitle: "Elimina",
      deleteConvConfirm: "Eliminare questa conversazione?",
      inputDesc: "Poni una domanda su leadership, dinamiche di team, comunicazione o scegli un prompt di esempio.",
      promptSearchPlaceholder: "Cerca prompt di esempio...",
      examplePromptsBtn: "Prompt di esempio",
      noPromptResults: (q: string) => `Nessun prompt trovato per "${q}"`,
      requireAnalysisTitle: "Analizza prima un ruolo",
      copyAnswer: "Copia risposta",
      goldenSaved: "Salvato come risposta di riferimento",
      goldenSave: "Salva come risposta di riferimento (admin)",
      suggestionsLabel: "Suggerimenti",
      loadingDefault: "Generazione della risposta...",
      inputPlaceholder: "Poni una domanda...",
      uploadImage: "Carica immagine",
      uploadDoc: "Carica PDF / documento di testo",
      errorOverloaded: "Il coach è momentaneamente sovraccarico. Riprova tra qualche secondo.",
      errorQuota: "La quota IA della tua organizzazione è esaurita. Contatta il tuo amministratore per aumentare il limite o resettare il contatore.",
      errorTimeout: "La richiesta ha impiegato troppo tempo. Riprova: per domande complesse, prova a formularle in modo più breve.",
      errorTimeoutShort: "La richiesta ha impiegato troppo tempo. Riprova.",
      errorTech: "Si è verificato un problema tecnico. Riprova.",
      exportHeader: "Louis — Trascrizione della conversazione",
      exportedAt: (d: string, t: string) => `Esportato il ${d} alle ${t}`,
      exportLabelQuestion: "Domanda",
      exportLabelCoach: "Coach",
      welcome: "Benvenuto da Louis — il tuo coach bioLogic per le decisioni nel momento giusto.\n\nTi supporto su domande di leadership, decisioni HR, assessment, colloqui e comunicazione.\n\nCome posso aiutarti?",
      imageWithText: "Immagine con testo",
      imageDownload: "Scarica immagine",
      imageOnly: "Solo immagine (senza testo)",
      attachmentAlt: "Allegato",
      docReading: "Lettura del documento...",
      roleRequired: "(ruolo richiesto)",
      aiImageNote: "[Un'immagine generata dall'IA è stata creata in questo passaggio]",
    },
    jobcheck: {
      pageTitle: "bioLogic JobCheck",
      pageSubtitle: "Valuta l'adeguatezza strutturale tra il profilo del ruolo e il profilo della persona.",
      printButton: "Stampa",
      printTooltip: "Scegli 'Salva come PDF' nella finestra di stampa",
      noAnalysisTitle: "Nessuna analisi disponibile",
      noAnalysisDesc: "Crea prima un profilo del ruolo per eseguire il JobCheck.",
      gotoDataEntry: "Vai all'inserimento dati",
      summaryRole: "Ruolo",
      summaryTaskStructure: "Struttura dei compiti",
      summaryWorkStyle: "Stile di lavoro",
      summarySuccessFocus: "Focus sul successo",
      summaryLeadership: "Leadership",
      summaryCompetenceCount: "Numero di competenze",
      summaryNotDefined: "Non definito",
      countActivities: "attività",
      countHumanSkills: "competenze umane",
      countLeadership: "leadership",
      taskStructureLabels: {
        "überwiegend operativ": "Operatività quotidiana",
        "überwiegend systemisch": "Coordinamento ed esecuzione nel flusso di lavoro",
        "überwiegend strategisch": "Analisi, pianificazione e gestione strategica",
        "Gemischt": "Mix equilibrato",
      } as Record<string, string>,
      workStyleLabels: {
        "Umsetzungsorientiert": "Realizzazione e risultati",
        "Daten-/prozessorientiert": "Analisi e struttura",
        "Menschenorientiert": "Collaborazione e comunicazione",
        "Ausgewogen": "Mix equilibrato",
      } as Record<string, string>,
      leadershipLabels: {
        "Keine": "Nessuna responsabilità di leadership",
        "Projekt-/Teamkoordination": "Coordinamento di progetto o team",
        "Fachliche Führung": "Leadership funzionale",
        "Disziplinarische Führung mit Ergebnisverantwortung": "Leadership con responsabilità sui risultati",
      } as Record<string, string>,
      successFocusLabels: [
        "Risultati e raggiungimento degli obiettivi",
        "Collaborazione e network",
        "Innovazione e cambiamento",
        "Processi ed efficienza",
        "Qualità funzionale ed expertise",
        "Comunicazione e influenza",
      ] as string[],
      analyseAccordionTitle: "Analisi — Profilo target / reale",
      reportAccordionTitle: "Rapporto JobCheck",
      sollHeader: "Profilo target (ruolo)",
      istHeader: "Profilo reale (persona)",
      istDescription: "Sposta i cursori per inserire il profilo della persona. I valori vengono normalizzati automaticamente.",
      labelImpulsiv: "Ritmo e Decisione",
      labelIntuitiv: "Comunicazione e Relazioni",
      labelAnalytisch: "Struttura e Rigore",
      normalizedNote: "Profilo normalizzato (max. 67% per componente)",
      roleDominanceText: (compLabel: string, dominanceText: string) =>
        `La logica dominante del ruolo è ${compLabel}: ${dominanceText}.`,
      candDominancePrefix: "La logica dominante della persona è ",
      candDominanceMiddle: ": ",
      createReportButton: "Crea rapporto",
      reportEmptyHint: "Inserisci prima il profilo reale e clicca su \"Crea rapporto\".",
    },
    teamcheckReport: {
      loadingTitle: "Creazione dell'analisi del team",
      loadingBody: "I testi vengono generati sulla base del profilo. Di solito ci vogliono 15-25 secondi.",
    },
  },
} as const;

export type UIDict = typeof UI.de;

export function useUI(): UIDict {
  const { region } = useRegion();
  if (region === "EN") return UI.en as unknown as UIDict;
  if (region === "FR") return UI.fr as unknown as UIDict;
  if (region === "IT") return UI.it as unknown as UIDict;
  return UI.de;
}

export function getUI(region: string): UIDict {
  if (region === "EN") return UI.en as unknown as UIDict;
  if (region === "FR") return UI.fr as unknown as UIDict;
  if (region === "IT") return UI.it as unknown as UIDict;
  return UI.de;
}
