import { useRegion } from "./region";

type UILang = "de" | "en";

export const UI = {
  de: {
    nav: {
      home: "Home",
      homeSub: "",
      jobcheck: "JobCheck",
      jobcheckSub: "Stellenanalyse",
      matchcheck: "MatchCheck",
      matchcheckSub: "Stelle ↔ Person",
      teamcheck: "TeamCheck",
      teamcheckSub: "Teamstruktur",
      coach: "Louis (KI-Coach)",
      coachSub: "Führung & Entwicklung",
      courses: "Kursbereich",
      coursesSub: "Lernmodule",
      regionTitle: "Sprachregion",
      regionLabel: (l: string) => `Sprachregion: ${l}`,
      firmaDashboard: "Firmen-Dashboard",
      userManagement: "Benutzerverwaltung",
      logout: "Abmelden",
    },
    footer: {
      aiQuotaTitle: (used: number, total: number, reset: string) =>
        `${used} von ${total} KI-Anfragen genutzt\nAutomatische Zurücksetzung am ${reset}`,
      aiPrefix: "KI:",
      aiOf: "von",
      aiLeft: "übrig",
      resetOn: "Reset am",
      accessUntil: "Freigeschaltet bis:",
      imprint: "Impressum",
      privacy: "Datenschutz",
      disclaimer: "Disclaimer",
    },
    region: {
      DE: "Deutschland",
      CH: "Schweiz",
      AT: "Österreich",
      EN: "English",
    },
    home: {
      resetTitle: "Bist du sicher?",
      resetBody: "Alle eingegebenen Daten werden gelöscht.",
      cancel: "Abbrechen",
      continue: "Weiter",
      fileError: "Die Datei konnte nicht gelesen werden.",
      jobcheckTitle: "Stellenanalyse",
      jobcheckSubtitle: "Strukturelle Passung für sichere Besetzungsentscheidungen",
      jobcheckDesc: "Definiere eine Stelle und analysiere die strukturelle Passung. Die Analyse liefert klare Handlungsempfehlungen für Besetzung, Führung und Zusammenarbeit.",
      newAnalysis: "Neue Analyse",
      openAnalysis: "Analyse öffnen",
      jobcheckBullets: [
        "Wissenschaftlich fundierte Methodik",
        "Klare Entscheidungsstruktur",
        "Objektive Personalentscheidungen",
        "Transparente Ergebnislogik",
        "Reduziert Fehlbesetzungsrisiken",
        "Passgenaue Rollenbesetzung",
      ],
      coachTitle: "Louis",
      coachSubtitle: "Coach für Entscheidungen im richtigen Moment",
      coachDesc: "Nutze Louis für Recruiting, Teamfragen, Gesprächsvorbereitung und konkrete Handlungsempfehlungen – jederzeit, auch ohne Analyse.",
      openCoach: "Louis öffnen",
      coachBullets: [
        "Recruiting und Stellenanzeigen",
        "Gesprächsvorbereitung",
        "Analyse von Teamkonstellationen",
        "Konfliktmuster erkennen und lösen",
        "Rollenspiele und Gesprächssimulation",
        "Quellenbasierte Führungsberatung",
      ],
    },
    coach: {
      pageTitle: "Louis",
      pageSubtitle: "Dein KI-Coach für Führung, HR und Teamfragen",
      profileActive: "Profil aktiv",
      historyTitle: "Verlauf",
      historyButtonTitle: "Gesprächsverlauf",
      newConvTitle: "Neue Unterhaltung",
      newConvButton: "Neue Unterhaltung",
      exportTitle: "Gespräch als TXT exportieren",
      clearChatTitle: "Gespräch löschen",
      clearChatConfirm: "Möchtest du das aktuelle Gespräch wirklich löschen?",
      historySearchPlaceholder: "Verlauf durchsuchen...",
      noHits: "Keine Treffer.",
      noConversations: "Noch keine gespeicherten Gespräche.",
      renameTitle: "Umbenennen",
      pinTitle: "Anpinnen",
      unpinTitle: "Lösen",
      deleteTitle: "Löschen",
      deleteConvConfirm: "Diese Unterhaltung wirklich löschen?",
      inputDesc: "Stell eine Frage zu Führung, Teamdynamik, Kommunikation oder nutze einen Musterprompt.",
      promptSearchPlaceholder: "Musterprompt suchen…",
      examplePromptsBtn: "Musterprompts",
      noPromptResults: (q: string) => `Keine Prompts gefunden für „${q}"`,
      requireAnalysisTitle: "Bitte zuerst eine Stelle analysieren",
      copyAnswer: "Antwort kopieren",
      goldenSaved: "Als Golden Answer gespeichert",
      goldenSave: "Als Golden Answer speichern (Admin)",
      suggestionsLabel: "Vorschläge",
      loadingDefault: "Antwort wird erstellt...",
      inputPlaceholder: "Frage stellen...",
      uploadImage: "Bild hochladen",
      uploadDoc: "PDF / Textdokument hochladen",
      errorOverloaded: "Der Coach ist gerade kurz überlastet – bitte in ein paar Sekunden nochmal probieren.",
      errorQuota: "Das KI-Kontingent eurer Organisation ist leider aufgebraucht. Bitte wende dich an euren Administrator, um das Limit zu erhöhen oder den Zähler zurückzusetzen.",
      errorTimeout: "Die Anfrage hat zu lange gedauert. Bitte versuche es erneut – bei komplexen Fragen kann es helfen, die Frage kürzer zu formulieren.",
      errorTimeoutShort: "Die Anfrage hat zu lange gedauert. Bitte versuche es erneut.",
      errorTech: "Entschuldigung, es ist ein technisches Problem aufgetreten. Bitte versuche es erneut.",
      exportHeader: "Louis – Gesprächsprotokoll",
      exportedAt: (d: string, t: string) => `Exportiert am ${d} um ${t}`,
      exportLabelQuestion: "Frage",
      exportLabelCoach: "Coach",
      welcome: "Willkommen bei Louis – deinem bioLogic Coach für Entscheidungen im richtigen Moment.\n\nIch unterstütze dich bei Fragen rund um Führung, Personalentscheidungen, Assessment, Bewerbungsgespräche und Kommunikation.\n\nWie kann ich dir helfen?",
      imageWithText: "Bild mit Text",
      imageDownload: "Bild herunterladen",
      imageOnly: "Nur Bild (ohne Text)",
      attachmentAlt: "Anhang",
      docReading: "Dokument wird gelesen...",
      roleRequired: "(Stelle erforderlich)",
      aiImageNote: "[KI-generiertes Bild wurde in diesem Schritt erstellt]",
    },
  },
  en: {
    nav: {
      home: "Home",
      homeSub: "",
      jobcheck: "JobCheck",
      jobcheckSub: "Role analysis",
      matchcheck: "MatchCheck",
      matchcheckSub: "Role ↔ Person",
      teamcheck: "TeamCheck",
      teamcheckSub: "Team structure",
      coach: "Louis (AI Coach)",
      coachSub: "Leadership & development",
      courses: "Courses",
      coursesSub: "Learning modules",
      regionTitle: "Language region",
      regionLabel: (l: string) => `Language region: ${l}`,
      firmaDashboard: "Company dashboard",
      userManagement: "User management",
      logout: "Log out",
    },
    footer: {
      aiQuotaTitle: (used: number, total: number, reset: string) =>
        `${used} of ${total} AI requests used\nAutomatic reset on ${reset}`,
      aiPrefix: "AI:",
      aiOf: "of",
      aiLeft: "left",
      resetOn: "Reset on",
      accessUntil: "Access until:",
      imprint: "Imprint",
      privacy: "Privacy",
      disclaimer: "Disclaimer",
    },
    region: {
      DE: "Germany",
      CH: "Switzerland",
      AT: "Austria",
      EN: "English",
    },
    home: {
      resetTitle: "Are you sure?",
      resetBody: "All entered data will be deleted.",
      cancel: "Cancel",
      continue: "Continue",
      fileError: "The file could not be read.",
      jobcheckTitle: "Role analysis",
      jobcheckSubtitle: "Structural fit for confident hiring decisions",
      jobcheckDesc: "Define a role and analyse its structural fit. The analysis delivers clear recommendations for hiring, leadership and collaboration.",
      newAnalysis: "New analysis",
      openAnalysis: "Open analysis",
      jobcheckBullets: [
        "Scientifically grounded methodology",
        "Clear decision structure",
        "Objective people decisions",
        "Transparent reasoning",
        "Reduces mis-hire risk",
        "Precise role placement",
      ],
      coachTitle: "Louis",
      coachSubtitle: "Coach for decisions at the right moment",
      coachDesc: "Use Louis for recruiting, team questions, interview preparation and concrete recommendations – anytime, even without an analysis.",
      openCoach: "Open Louis",
      coachBullets: [
        "Recruiting and job postings",
        "Interview preparation",
        "Analysing team constellations",
        "Spotting and resolving conflict patterns",
        "Role play and conversation simulation",
        "Source-based leadership advice",
      ],
    },
    coach: {
      pageTitle: "Louis",
      pageSubtitle: "Your AI coach for leadership, HR and team questions",
      profileActive: "Profile active",
      historyTitle: "History",
      historyButtonTitle: "Conversation history",
      newConvTitle: "New conversation",
      newConvButton: "New conversation",
      exportTitle: "Export conversation as TXT",
      clearChatTitle: "Delete conversation",
      clearChatConfirm: "Do you really want to delete the current conversation?",
      historySearchPlaceholder: "Search history...",
      noHits: "No results.",
      noConversations: "No saved conversations yet.",
      renameTitle: "Rename",
      pinTitle: "Pin",
      unpinTitle: "Unpin",
      deleteTitle: "Delete",
      deleteConvConfirm: "Really delete this conversation?",
      inputDesc: "Ask a question about leadership, team dynamics, communication or pick an example prompt.",
      promptSearchPlaceholder: "Search example prompts…",
      examplePromptsBtn: "Example prompts",
      noPromptResults: (q: string) => `No prompts found for „${q}"`,
      requireAnalysisTitle: "Please analyse a role first",
      copyAnswer: "Copy answer",
      goldenSaved: "Saved as Golden Answer",
      goldenSave: "Save as Golden Answer (admin)",
      suggestionsLabel: "Suggestions",
      loadingDefault: "Generating answer...",
      inputPlaceholder: "Ask a question...",
      uploadImage: "Upload image",
      uploadDoc: "Upload PDF / text document",
      errorOverloaded: "The coach is briefly overloaded – please try again in a few seconds.",
      errorQuota: "Your organisation's AI quota has been used up. Please contact your administrator to raise the limit or reset the counter.",
      errorTimeout: "The request took too long. Please try again – for complex questions it can help to phrase them more briefly.",
      errorTimeoutShort: "The request took too long. Please try again.",
      errorTech: "Sorry, a technical problem occurred. Please try again.",
      exportHeader: "Louis – conversation transcript",
      exportedAt: (d: string, t: string) => `Exported on ${d} at ${t}`,
      exportLabelQuestion: "Question",
      exportLabelCoach: "Coach",
      welcome: "Welcome to Louis – your bioLogic coach for decisions at the right moment.\n\nI support you with questions on leadership, people decisions, assessment, interviews and communication.\n\nHow can I help you?",
      imageWithText: "Image with text",
      imageDownload: "Download image",
      imageOnly: "Image only (no text)",
      attachmentAlt: "Attachment",
      docReading: "Reading document...",
      roleRequired: "(role required)",
      aiImageNote: "[An AI-generated image was created in this step]",
    },
  },
} as const;

export type UIDict = typeof UI.de;

export function useUI(): UIDict {
  const { region } = useRegion();
  return region === "EN" ? (UI.en as unknown as UIDict) : UI.de;
}

export function getUI(region: string): UIDict {
  return region === "EN" ? (UI.en as unknown as UIDict) : UI.de;
}
