const BASIS_BERUFE: string[] = [
  "Accountant","Account Manager","Abteilungsleiter","Aktuar","Altenpfleger","Analyst","Anästhesist",
  "Anlagenmechaniker","Anlagenmechaniker Sanitär-, Heizungs- und Klimatechnik","Anwendungsentwickler",
  "Apotheker","Applikationsingenieur","Arbeitsmediziner","Arbeitsvorbereiter","Architekt","Archivar",
  "Arzt","Assistenzarzt","Auditor","Aufzugsmonteur","Augenarzt","Augenoptiker","Automobilkaufmann",
  "Außendienstmitarbeiter","Automatisierungstechniker","Bäcker","Backend-Entwickler","Bademeister",
  "Bankkaufmann","Barista","Barkeeper","Berufsschullehrer","Busfahrer","Bauingenieur","Bauleiter",
  "Bauzeichner","Berater","Bereichsleiter","Betriebselektriker","Betriebsleiter","Betriebswirt",
  "Bibliotheksassistent","Bibliothekar","Bildungsreferent","Biologe","Biotechnologe","Bodenleger",
  "Brandschutzbeauftragter","Brauer","Buchbinder","Buchhalter","Bühnentechniker","Bürokaufmann",
  "Business Analyst","Business Controller","Business Development Manager","CAD-Konstrukteur",
  "Call-Center-Agent","Case Manager","Category Manager","CEO","CFO","Change Manager","Chemieingenieur",
  "Chemielaborant","Chemiker","Chiropraktiker","CIO","Cloud Architect","Cloud Engineer","CNC-Fräser",
  "CNC-Programmierer","Coach","Community Manager","Compliance Manager","Compliance Officer",
  "Content Creator","Content Manager","Content Strategist","Controller","COO","Copywriter",
  "CRM Manager","CTO","Customer Success Manager","Cybersecurity Analyst","Dachdecker","Data Analyst",
  "Data Engineer","Data Scientist","Datenbankadministrator","Datenmanager","Dekorateur","Designer",
  "DevOps Engineer","Diabetesberater","Diätassistent","Diplomat","Direktor","Disponent","Dolmetscher",
  "Dozent","Drechsler","Dreher","Drogist","Drucker","E-Commerce Manager","Einkäufer","Einkaufsleiter",
  "Eisenbahner","Elektriker","Elektroingenieur","Elektromeister","Elektroniker","Elektrotechniker",
  "Energieberater","Energiemanager","Entsorgungsfachkraft","Entwicklungsingenieur","Erzieher",
  "ESG Manager","Event Manager","Facharzt","Fachinformatiker","Fachlagerist","Fachkraft für Arbeitssicherheit",
  "Fachkraft für Lagerlogistik","Fachkraft für Lebensmitteltechnik","Fachkraft für Metalltechnik",
  "Fachkraft für Schutz und Sicherheit","Fahrzeuglackierer","Fahrzeugmechaniker","Fahrlehrer",
  "Fertigungsingenieur","Fertigungsleiter","Fertigungsmechaniker","Fertigungsplaner","Filialleiter",
  "Finanzanalyst","Finanzberater","Finanzcontroller","Finanzmakler","Finanzmanager","Finanzplaner",
  "Feuerwehrmann","Fleischer","Fliesenleger","Florist","Fluglotse","Flugzeugmechaniker",
  "Forscher","Forschungsleiter","Forstwirt","Fotograf","Franchise-Manager","Frontend-Entwickler",
  "Fullstack-Entwickler","Gabelstaplerfahrer","Gärtner","Gastronom","Gebäudereiniger",
  "Gebäudetechniker","Geburtshelfer","Geologe","Geomatiker","Gerichtsvollzieher","Gerüstbauer",
  "Geschäftsführer","Gesundheits- und Krankenpfleger","Gesundheitsmanager","Gießer","Glasapparatebauer",
  "Glaser","Gleisbauer","Goldschmied","Grafiker","Grafikdesigner","Grundschullehrer","Gruppenleiter",
  "Gutachter","Gymnasiallehrer","Gynäkologe","Handelsvertreter","Handwerksmeister","Hauptschullehrer",
  "Haustechniker","Head of Engineering","Head of Finance","Head of HR","Head of IT","Head of Marketing",
  "Head of Operations","Head of Product","Head of Sales","Hebamme","Heilpraktiker","Heizungsbauer",
  "Heizungsinstallateur","Helfer Produktion","Hoteldirektor","Hotelfachmann","HR Business Partner",
  "HR Generalist","HR Manager","Hörgeräteakustiker","Hygienefachkraft","Hypothekenberater",
  "Illustrator","Immobilienkaufmann","Immobilienmakler","Immobilienverwalter","Incident Manager",
  "Industriedesigner","Industrieelektriker","Industriekaufmann","Industriemechaniker",
  "Industriemeister","Informatiker","Informatikkaufmann","Informationssicherheitsbeauftragter",
  "Ingenieur","Innenarchitekt","Innovation Manager","Installateur","Instandhalter",
  "Intensivpfleger","Interimsmanager","Internist","Investment Manager","IT-Administrator",
  "IT-Architekt","IT-Berater","IT-Consultant","IT-Koordinator","IT-Leiter","IT-Manager",
  "IT-Projektleiter","IT-Security Engineer","IT-Systemkaufmann","Journalist","Jurist","Kältetechniker",
  "Kameramann","Kanalbauer","Kardiologe","Kartograf","Kaufmann für Büromanagement",
  "Kaufmann für Digitalisierungsmanagement","Kaufmann für Groß- und Außenhandel",
  "Kaufmann für Spedition und Logistik","Kaufmann für Versicherungen und Finanzen",
  "Kaufmann im E-Commerce","Kaufmann im Einzelhandel","Kaufmann im Gesundheitswesen",
  "Key Account Manager","Kinderpfleger","Kita-Leitung","Klempner","KI-Ingenieur",
  "Klimatechniker","Koch","Kommunikationsdesigner","Kommunikationsmanager","Konditor",
  "Konstrukteur","Konstruktionsingenieur","Koordinator","Korrespondent","Krankenpfleger",
  "Küchenmeister","Kulturmanager","Kundenberater","Kundendienstmitarbeiter","Kunststofftechniker",
  "Kurier","Laborant","Laborleiter","Labortechniker","Lackierer","Lagerist","Lagerleiter",
  "Landmaschinenmechaniker","Landschaftsarchitekt","Landschaftsgärtner","Landwirt","Lean Manager",
  "Lehrer","Lehrgangsleiter","Leiter Einkauf","Leiter Fertigung","Leiter Finanzen",
  "Leiter Logistik","Leiter Marketing","Leiter Personal","Leiter Produktion",
  "Leiter Qualitätssicherung","Leiter Vertrieb","Leitender Angestellter","Lektor","Lichtdesigner",
  "Logistikleiter","Logistikmanager","Logistikplaner","Logopäde","Lokführer","Lüftungstechniker",
  "Maler","Maler und Lackierer","Manager","Managing Director","Marketing Analyst",
  "Marketing Automation Manager","Marketing Manager","Marketingleiter","Marktforscher",
  "Maschinenbauingenieur","Maschinenführer","Maschinist","Masseur","Maurer","Mechatroniker",
  "Mediendesigner","Mediengestalter","Medienkaufmann","Medizincontroller","Mediziner",
  "Medizinischer Fachangestellter","Medizinphysiker","Medizintechniker","Meister",
  "Messtechniker","Metallbauer","Metallschleifer","Meteorologe","Mikrobiologe","Milchtechnologe",
  "Mitarbeiter Einkauf","Mitarbeiter Logistik","Mitarbeiter Qualitätssicherung",
  "Mitarbeiter Vertrieb","Möbeltischler","Moderator","Monteur","Motivationstrainer",
  "Müller","Musiklehrer","Musiker","Netzwerktechniker","Neurologe","Notar","Notfallsanitäter",
  "Oberarzt","Office Manager","Ökonom","Onkologe","Online Marketing Manager","Operationstechnischer Assistent",
  "Optiker","Ordnungsamtsmitarbeiter","Organisationsberater","Orthopäde","Orthopädietechniker",
  "Osteopath","Pädagoge","Paketzusteller","Patentanwalt","Patentingenieur","Pathologe",
  "Performance Marketing Manager","Personal Trainer","Personalberater","Personaldisponent",
  "Personalentwickler","Personalleiter","Personalreferent","Personalsachbearbeiter",
  "Pflegedienstleitung","Pflegefachkraft","Pfleger","Pharmaberater","Pharmareferent",
  "Pharmatechnologe","Pharmazeut","Physiotherapeut","Physiker","Pilot","Pizzabäcker",
  "Planer","Planungsleiter","Podologe","Polier","Polizist","Postbote","PR-Berater","PR-Manager",
  "Praxismanager","Prüfer","Prüfingenieur","Prüftechniker","Pressesprecher","Privatdetektiv",
  "Process Engineer","Product Manager","Product Owner","Produktdesigner","Produktentwickler",
  "Produktionshelfer","Produktionsleiter","Produktionsmitarbeiter","Produktionsplaner",
  "Produktmanager","Professor","Programmierer","Projekt-Controller","Projektassistent",
  "Projektingenieur","Projektleiter","Projektmanager","Projektplaner","Prozessberater",
  "Prozessingenieur","Prozessmanager","Prozessoptimierer","Psychiater","Psychologe",
  "Psychotherapeut","Public Relations Manager","Qualitätsbeauftragter","Qualitätsingenieur",
  "Qualitätsmanager","Qualitätsprüfer","Qualitätssicherer","Radiologie-Technologe",
  "Raumpfleger","Realschullehrer","Rechnungsprüfer","Rechtsanwalt","Rechtsanwaltsfachangestellte",
  "Redakteur","Referent","Reformhauskaufmann","Regionaldirektor","Regionalleiter",
  "Reiseberater","Reiseleiter","Reiseverkehrskaufmann","Rendant","Restaurantfachmann",
  "Restaurator","Rettungsassistent","Rettungssanitäter","Revisor","Richter","Risikomanager",
  "Robotik-Ingenieur","Rohrleitungsbauer","Sachbearbeiter","Sachverständiger","SAP-Berater",
  "Sales Manager","Sanitäter","Schädlingsbekämpfer","Schaffner","Schauspieler",
  "Schichtführer","Schichtleiter","Schiffsmechaniker","Schlosser","Schneider","Schornsteinfeger",
  "Schreiner","Schulleiter","Schweißer","Security Engineer","SEO Manager","SEO-Spezialist",
  "Serviceleiter","Servicemitarbeiter","Servicetechniker","SHK-Installateur","Sicherheitsbeauftragter",
  "Social Media Manager","Software Architect","Software Engineer","Softwareentwickler",
  "Softwaretester","Sonderpädagoge","Sonnenschutztechniker","Sozialarbeiter","Sozialpädagoge",
  "Spediteur","Spieleentwickler","Sportlehrer","Sportmanager","Sporttherapeut","Sprachtherapeut",
  "Staatsanwalt","Stadtplaner","Standesbeamter","Statistiker","Steuerberater","Steuerfachangestellter",
  "Steuerfahnder","Storemanager","Straßenbauer","Strategieberater","Studioleiter","Supply Chain Manager",
  "Sustainability Manager","System Engineer","Systemadministrator","Systemarchitekt",
  "Tagesstättenleitung","Taucher","Teamleiter","Techniker","Technischer Einkäufer",
  "Technischer Leiter","Technischer Redakteur","Technischer Zeichner","Technologieberater",
  "Telekommunikationstechniker","Terminplaner","Testkaufmann","Therapeut","Tierarzt",
  "Tierpfleger","Tischler","Tischlermeister","Tonmeister","Tourismusmanager","Toxikologe",
  "Trainer","Transformationsmanager","Triebfahrzeugführer","Trockenbaumonteur","TÜV-Prüfer",
  "Übersetzer","Uhrmacher","Umweltberater","Umweltingenieur","Umweltmanager","Umwelttechniker",
  "Underwriter","Unfallchirurg","Unternehmensentwickler","Unternehmensberater",
  "UX Designer","UX Researcher","Verfahrensingenieur","Verfahrensmechaniker","Verfahrenstechniker",
  "Verkäufer","Verkaufsberater","Verkaufsfahrer","Verkaufsleiter","Vermessungsingenieur",
  "Vermessungstechniker","Vermögensberater","Versandmitarbeiter","Versicherungskaufmann",
  "Versicherungsmakler","Versorgungsingenieur","Vertriebsassistent","Vertriebsbeauftragter",
  "Vertriebsingenieur","Vertriebsinnendienst","Vertriebsleiter","Vertriebsmitarbeiter",
  "Verwaltungsangestellter","Verwaltungsfachangestellter","Verwaltungsleiter","Veterinär",
  "Virologe","Visual Merchandiser","Volksschullehrer","Vorstand","Warenprüfer",
  "Wärmetechniker","Webdesigner","Webentwickler","Weinbauer","Werkstattleiter","Werkstattmeister",
  "Werkstoffprüfer","Werkzeugmacher","Werkzeugmechaniker","Wirtschaftsinformatiker",
  "Wirtschaftsingenieur","Wirtschaftsprüfer","Wissenschaftlicher Mitarbeiter","Zahnarzt",
  "Zahntechniker","Zimmerer","Zimmermann","Zollbeamter","Zoologe","Zugbegleiter","Zerspanungsmechaniker",
  "Ökotrophologin","Pflegewissenschaftler","Prokurist","Rechtsreferendar","Rettungsingenieur",
  "Sachkundiger Planer","Schadensregulierer","Servicekaufmann","Sozialpädagogischer Assistent",
  "Stationsleitung","Studienrat","Supply Chain Analyst","Technischer Betriebswirt",
  "Technischer Sachverständiger","Testkäufer","Überprüfer","Umweltanalytiker","Urlaubsplaner",
  "Verlagslektor","Vermittler","Versorgungstechniker","Verwaltungswirt",
  "Wareneingangsbearbeiter","Werkschutzleiter","Wirtschaftsjurist","Wohnberater",
  "Zahnmedizinische Fachangestellte","Zentrallagerist","Zustellbasis-Leiter",
  "Betriebsrat","Datenschutzbeauftragter","Exportkaufmann","Importkaufmann",
  "Innendienstmitarbeiter","Kundenservice-Mitarbeiter","Markenmanager","Nachhaltigkeitsbeauftragter",
  "Personalcontroller","Preisanalyst","Produktionsingenieur","Programmmanager",
  "Qualitätsauditor","Reklamationsbearbeiter","Risikobewertungsanalyst","SAP-Entwickler",
  "Schulungsleiter","Speditionskaufmann","Syndikusanwalt","Technischer Projektleiter",
  "Umweltauditor","Validierungsingenieur","Vertragsmanager","Vorstandsassistent",
  "Wertpapierberater","Wissensmanager","Zolldeklarant","Automatisierungsingenieur",
  "Betriebsratsvorsitzender","Einkaufscontroller","Exportleiter","Fertigungskoordinator",
  "Handelsvertreter","Instandhaltungsleiter","Instandhaltungsmechaniker",
  "Industrieabwassertechniker","Instandhaltungstechniker","Kalkulator","Kesselwärter",
  "Kraftfahrer","Kranfahrer","Kunststoffschweißer","Laboringenieur","Logistiksachbearbeiter",
  "Materialplaner","Medizinproduktberater","Montageleiter","Netzwerkadministrator",
  "Oberbauleiter","Paketsortierer","Produktionskoordinator","Qualitätsplaner",
  "Rechnungswesen-Sachbearbeiter","Schaltschrankbauer","Sicherheitsingenieur",
  "Staplerfahrer","Straßenmeister","Technischer Sachbearbeiter","Transportleiter",
  "Umweltschutzbeauftragter","Verpackungsingenieur","Versandleiter","Versuchsingenieur",
  "Warenwirtschaftler","Werkplaner","Wärmebehandler","Zentraleinkäufer",
];

const ROLLEN_MIT_BRANCHEN: string[] = [
  "Account Manager","Abteilungsleiter","Außendienstmitarbeiter","Berater","Bereichsleiter",
  "Betriebsleiter","Business Development Manager","Category Manager","Change Manager",
  "Compliance Manager","Controller","Customer Success Manager","Disponent","E-Commerce Manager",
  "Einkäufer","Einkaufsleiter","Filialleiter","Finanzberater","Geschäftsführer","Gruppenleiter",
  "HR Business Partner","HR Manager","Ingenieur","IT-Berater","IT-Leiter","IT-Projektleiter",
  "Key Account Manager","Konstrukteur","Koordinator","Kundenberater","Lean Manager",
  "Leiter Einkauf","Leiter Fertigung","Leiter Logistik","Leiter Marketing","Leiter Personal",
  "Leiter Produktion","Leiter Qualitätssicherung","Leiter Vertrieb","Logistikleiter",
  "Marketing Manager","Marketingleiter","Meister","Monteur","Operations Manager",
  "Personalberater","Personalentwickler","Personalleiter","Product Manager","Product Owner",
  "Produktionsleiter","Produktmanager","Projektleiter","Projektmanager","Prozessmanager",
  "Qualitätsmanager","Qualitätsingenieur","Risikomanager","Sachbearbeiter","Sales Manager",
  "Schichtleiter","Servicetechniker","Supply Chain Manager","Teamleiter","Techniker",
  "Technischer Leiter","Trainer","Verkäufer","Verkaufsleiter","Vertriebsingenieur",
  "Vertriebsinnendienst","Vertriebsleiter","Vertriebsmitarbeiter","Vorstand","Werkstattleiter",
];

const TOP_BRANCHEN: string[] = [
  "Automobilindustrie","Maschinenbau","Elektrotechnik","Chemie","Pharma","Medizintechnik",
  "IT","Software","Telekommunikation","Finanzdienstleistungen","Banken","Versicherungen",
  "Immobilien","Handel","E-Commerce","Logistik","Transport","Energie","Erneuerbare Energien",
  "Bauwesen","Lebensmittelindustrie","Konsumgüter","Medien","Beratung","Unternehmensberatung",
  "Personalberatung","Luft- und Raumfahrt","Öffentlicher Dienst","Gesundheitswesen",
  "Biotechnologie","Halbleiter","Elektronik","Metallindustrie","Tourismus","Hotellerie",
  "Gastronomie","Bildung","Forschung","Landwirtschaft","Umwelttechnik","Gaming",
  "Kosmetik","Sicherheitstechnik","Gebäudetechnik","Automatisierung","Robotik",
  "Künstliche Intelligenz","FinTech","HealthTech","Pflege",
];

const CH_BERUFE: string[] = [
  "Polymechaniker","Automatiker","Elektroinstallateur EFZ","Fachmann Gesundheit EFZ",
  "Kaufmann EFZ","Detailhandelsfachmann EFZ","Informatiker EFZ","Konstrukteur EFZ",
  "Mediamatiker EFZ","Logistiker EFZ","Sanitärinstallateur EFZ","Heizungsinstallateur EFZ",
  "Elektroinstallateur","Hochbauzeichner EFZ","Tiefbauzeichner","Lüftungsanlagenbauer EFZ",
  "Anlagen- und Apparatebauer EFZ","Laborant EFZ","Produktionsmechaniker EFZ",
  "Metallbauer EFZ","Schreiner EFZ","Zimmermann EFZ","Maurer EFZ","Gärtner EFZ",
  "Fleischfachmann EFZ","Bäcker-Konditor EFZ","Milchtechnologe EFZ","Augenoptiker EFZ",
  "Dentalassistent EFZ","Fachmann Betreuung EFZ","Assistentin Gesundheit und Soziales EBA",
  "Eidg. dipl. Betriebswirtschafter","Eidg. dipl. Einkaufsfachmann","Eidg. dipl. Finanzplaner",
  "Eidg. dipl. Marketingleiter","Eidg. dipl. Verkaufsleiter","Eidg. dipl. HR-Leiter",
  "Eidg. dipl. Steuerexperte","Eidg. dipl. Wirtschaftsprüfer","Eidg. dipl. Immobilientreuhänder",
  "Technischer Kaufmann FA","Logistikfachmann FA","Personalfachmann FA","Marketingfachmann FA",
  "Verkaufsfachmann FA","Finanzplaner FA","Sozialversicherungsfachmann FA","Treuhänder FA",
  "Führungsfachmann FA","Ausbilder FA","Prozessfachmann FA",
];

const AT_BERUFE: string[] = [
  "Werkmeister","Denkmal-, Fassaden- und Gebäudereiniger","Installations- und Gebäudetechniker",
  "Metalltechniker","Elektrotechniker","Kraftfahrzeugtechniker","Tischlereitechniker",
  "Bautechnischer Zeichner","Verwaltungsassistent","Finanz- und Rechnungswesenassistent",
  "Betriebslogistikkaufmann","Großhandelskaufmann","Bürokaufmann","Einzelhandelskaufmann",
  "Speditionskaufmann AT","Versicherungskaufmann AT","Bankkaufmann AT","Pharmazeutisch-kaufmännische Assistenz",
  "Ordinationsassistenz","Diplomierte Gesundheits- und Krankenpflege","Pflegefachassistenz",
  "Medizinische Assistenzberufe","Magistra der Pharmazie","Amtsarzt",
];

const EXTRA_INTERNATIONAL: string[] = [
  "Scrum Master","Agile Coach","Release Manager","Site Reliability Engineer","Platform Engineer",
  "Machine Learning Engineer","AI Researcher","Blockchain Developer","Smart Contract Developer",
  "Growth Hacker","Growth Manager","Conversion Manager","Retention Manager","Pricing Analyst",
  "Revenue Manager","Yield Manager","Treasury Manager","Fund Manager","Portfolio Manager",
  "Wealth Manager","Private Banker","Credit Analyst","Underwriting Analyst","Claims Manager",
  "Actuary","Risk Analyst","Fraud Analyst","AML Analyst","KYC Analyst","Compliance Analyst",
  "Regulatory Affairs Manager","Clinical Research Associate","Medical Science Liaison",
  "Pharmacovigilance Officer","Drug Safety Associate","Quality Control Analyst",
  "Validation Engineer","Calibration Technician","Environmental Health and Safety Manager",
  "Occupational Health Specialist","Industrial Hygienist","Fire Safety Engineer",
  "Loss Prevention Manager","Chief Information Security Officer","Penetration Tester",
  "SOC Analyst","Threat Intelligence Analyst","Digital Forensics Investigator",
  "IT Auditor","Enterprise Architect","Solutions Architect","Technical Account Manager",
  "Customer Engineer","Field Application Engineer","Pre-Sales Engineer","Post-Sales Engineer",
  "Implementation Consultant","Onboarding Specialist","Training Manager","Learning Designer",
  "Instructional Designer","Curriculum Developer","E-Learning Developer","LMS Administrator",
  "Talent Acquisition Specialist","Employer Branding Manager","Diversity and Inclusion Manager",
  "Compensation and Benefits Manager","HRIS Analyst","People Analytics Manager",
  "Employee Experience Manager","Chief People Officer","Chief Revenue Officer",
  "Chief Technology Officer","Chief Operating Officer","Chief Financial Officer",
  "Chief Marketing Officer","Chief Product Officer","Chief Data Officer",
  "Chief Sustainability Officer","Chief Digital Officer","VP Engineering","VP Sales",
  "VP Marketing","VP Operations","VP Finance","VP Human Resources","VP Product",
  "Director of Engineering","Director of Sales","Director of Marketing",
  "Director of Operations","Director of Finance","Director of HR",
  "Program Director","Portfolio Director","Transformation Director",
  "Digital Transformation Manager","Innovation Manager","Venture Manager",
  "Corporate Development Manager","M&A Analyst","M&A Manager","Investor Relations Manager",
  "Sustainability Analyst","ESG Analyst","Carbon Footprint Analyst","Energy Auditor",
  "Renewable Energy Engineer","Solar Engineer","Wind Energy Engineer","Battery Engineer",
  "Hydrogen Engineer","Smart Grid Engineer","Power Systems Engineer",
  "Biomedical Engineer","Clinical Engineer","Prosthetics Engineer","Rehabilitation Engineer",
  "Food Scientist","Food Technologist","Nutritionist","Sommelier","Brewery Master",
  "Winemaker","Distiller","Agricultural Engineer","Precision Agriculture Specialist",
  "Horticulturist","Arborist","Marine Biologist","Ecologist","Conservation Scientist",
  "Wildlife Manager","Forest Manager","Park Ranger","Urban Planner","Traffic Engineer",
  "Railway Engineer","Aerospace Engineer","Avionics Engineer","Satellite Engineer",
  "Telecommunications Engineer","Network Engineer","RF Engineer","Fiber Optics Engineer",
  "Embedded Systems Engineer","Firmware Engineer","FPGA Engineer","ASIC Designer",
  "Chip Designer","Semiconductor Process Engineer","Clean Room Technician",
  "Materials Scientist","Metallurgist","Polymer Scientist","Ceramics Engineer",
  "Textile Engineer","Packaging Engineer","Print Production Manager",
  "Color Scientist","Typography Designer","Brand Manager","Brand Strategist",
  "Media Planner","Media Buyer","Affiliate Manager","Influencer Marketing Manager",
  "Podcast Producer","Video Producer","Animation Director","Game Designer",
  "Level Designer","Game Producer","QA Tester","Localization Manager",
  "Technical Writer","API Writer","Documentation Engineer","Knowledge Manager",
  "Records Manager","Information Architect","Taxonomist","Ontologist",
  "Search Engineer","NLP Engineer","Computer Vision Engineer","Robotics Engineer",
  "Automation Engineer","Control Systems Engineer","Instrumentation Engineer",
  "SCADA Engineer","PLC Programmer","Maintenance Engineer","Reliability Engineer",
  "Asset Manager","Facility Manager","Property Manager","Building Inspector",
  "Quantity Surveyor","Cost Engineer","Estimator","Procurement Manager",
  "Vendor Manager","Contract Manager","Bid Manager","Proposal Manager",
  "Grant Writer","Technical Recruiter","Executive Recruiter","Headhunter",
  "Staffing Manager","Workforce Planner","Organizational Development Consultant",
  "Change Consultant","Strategy Consultant","Management Consultant",
  "Technology Consultant","Digital Consultant","Financial Advisor",
  "Tax Consultant","Audit Manager","Internal Auditor","External Auditor",
  "Forensic Accountant","Management Accountant","Cost Accountant",
  "Payroll Manager","Accounts Payable Manager","Accounts Receivable Manager",
  "Credit Controller","Collections Manager","Billing Specialist",
  "Subscription Manager","Licensing Manager","Royalty Analyst",
  "Trade Compliance Officer","Export Control Officer","Customs Broker",
  "Import Specialist","Logistics Coordinator","Warehouse Manager",
  "Distribution Manager","Fleet Manager","Route Planner","Last Mile Specialist",
  "Fulfillment Manager","Inventory Manager","Demand Planner","Supply Planner",
  "Production Planner","Master Scheduler","Capacity Planner",
  "Continuous Improvement Manager","Six Sigma Black Belt","Kaizen Facilitator",
  "Value Stream Manager","Total Quality Manager","Statistical Process Control Analyst",
  "Test Engineer","Durability Engineer","Noise Vibration Harshness Engineer",
  "Crash Test Engineer","Emissions Engineer","Powertrain Engineer",
  "Chassis Engineer","Body Engineer","Interior Designer Automotive",
  "Exterior Designer Automotive","Color and Trim Designer",
  "Aerodynamics Engineer","CFD Engineer","FEA Engineer","Simulation Engineer",
  "Digital Twin Engineer","Model Based Systems Engineer","Systems Engineer",
  "Requirements Engineer","Configuration Manager","Technical Program Manager",
  "Engineering Manager","Principal Engineer","Staff Engineer","Fellow Engineer",
  "Distinguished Engineer","Chief Architect","Chief Scientist",
  "Research Director","Lab Manager","Principal Investigator","Postdoctoral Researcher",
  "Research Associate","Research Assistant","Clinical Trial Manager",
  "Biostatistician","Epidemiologist","Health Economist","Market Access Manager",
  "Medical Writer","Medical Monitor","Medical Director",
  "Nursing Director","Ward Manager","Operating Room Manager",
  "Emergency Room Manager","ICU Manager","Radiology Manager",
  "Laboratory Director","Pathology Manager","Pharmacy Manager",
  "Hospital Administrator","Health Information Manager","Patient Safety Officer",
  "Quality Improvement Officer","Infection Control Specialist",
  "Sterile Processing Manager","Biomedical Equipment Technician",
  "Dental Technician","Dental Hygienist","Optometrist","Audiologist",
  "Speech Language Pathologist","Occupational Therapist","Physical Therapist",
  "Respiratory Therapist","Radiation Therapist","Nuclear Medicine Technologist",
  "Sonographer","Phlebotomist","Medical Coder","Medical Biller",
  "Health Coach","Wellness Coordinator","Corporate Wellness Manager",
  "Ergonomist","Kinesiologist",
];

const SPEZIALISIERUNGEN: string[] = [
  "B2B","B2C","International","DACH","Digital","Senior","Inhouse","Interim","Strategisch","Operativ","Technisch","Kaufmännisch",
];

const ZUSATZ_ROLLEN: string[] = [
  "Arzt","Architekt","Apotheker","Bankkaufmann","Bauingenieur","Bauleiter",
  "Betriebswirt","Biologe","Chemiker","Data Analyst","Data Scientist",
  "Elektroingenieur","Erzieher","Fachinformatiker","Forscher","Grafiker",
  "Immobilienmakler","Industriekaufmann","Journalist","Jurist","Koch",
  "Krankenpfleger","Laborant","Lehrer","Maschinenbauingenieur","Mechatroniker",
  "Mediengestalter","Notar","Pädagoge","Pharmazeut","Physiotherapeut",
  "Polizist","Psychologe","Rechtsanwalt","Redakteur","Sozialarbeiter",
  "Steuerberater","Tierarzt","Übersetzer","Webentwickler","Wirtschaftsinformatiker",
  "Wirtschaftsingenieur","Zahnarzt","Zerspanungsmechaniker","Elektriker",
  "Tischler","Zimmermann","Maurer","Dachdecker","Klempner","Maler",
];

export function generateSeedProfessions(targetCount: number = 7500): string[] {
  const set = new Set<string>();

  for (const b of BASIS_BERUFE) set.add(b);
  for (const b of CH_BERUFE) set.add(b);
  for (const b of AT_BERUFE) set.add(b);
  for (const b of EXTRA_INTERNATIONAL) set.add(b);

  for (const rolle of ROLLEN_MIT_BRANCHEN) {
    if (set.size >= targetCount) break;
    for (const branche of TOP_BRANCHEN) {
      if (set.size >= targetCount) break;
      set.add(`${rolle} ${branche}`);
    }
  }

  if (set.size < targetCount) {
    for (const rolle of ROLLEN_MIT_BRANCHEN) {
      if (set.size >= targetCount) break;
      for (const spez of SPEZIALISIERUNGEN) {
        if (set.size >= targetCount) break;
        set.add(`${rolle} (${spez})`);
      }
    }
  }

  if (set.size < targetCount) {
    for (const rolle of ZUSATZ_ROLLEN) {
      if (set.size >= targetCount) break;
      for (const branche of TOP_BRANCHEN) {
        if (set.size >= targetCount) break;
        set.add(`${rolle} ${branche}`);
      }
    }
  }

  const arr = Array.from(set).sort((a, b) => a.localeCompare(b, "de"));
  return arr.slice(0, targetCount);
}
